# Generated by Django 5.1.3 on 2024-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_tg', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('session_type', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('post_id', models.IntegerField()),
                ('post_name', models.TextField()),
                ('branch_id', models.IntegerField()),
                ('branch_name', models.CharField(max_length=200)),
                ('rrs_name', models.CharField(max_length=100)),
                ('division_name', models.CharField(max_length=100)),
                ('user_mail', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(blank=True)),
                ('discussion_status', models.BooleanField(default='False')),
                ('discussion_number', models.IntegerField(blank=True, default='0')),
                ('state_point', models.IntegerField(default='0')),
                ('start_message_id', models.IntegerField(default='0')),
                ('employee_status', models.BooleanField(default='False')),
                ('holiday_status', models.BooleanField(blank=True)),
                ('admin_status', models.BooleanField(default='False')),
            ],
        ),
    ]
